### PR TITLE
H2-regulated star formation tests and fixes 

### PR DESCRIPTION
**Pull request by tumlinson**
Implements H2-regulated star formation for enzo-foggie. This branch / PR does the following:

(1) adds a parameter "H2StarMakerUseLocalDensityMax" (default value 0. If this == 1 in the parameter file, star_maker_H2reg.F will only form star particles in a cell if that cell is a local density maximum.
(2) adds a parameter "H2StarMakerWriteStarLogFiles" so that writing the starlog files is controlled by an Enzo parameter rather than a C preprocessor directive. #ifdef STAR_LOG is now removed and replaced by H2StarMakerWriteStarLogFiles (default value 0, files are not written). If H2StarMakerWriteStarLogFiles = 1 in the parameter file they are created.

### CODE REVIEW

**Comment by clairekope** [comment]
@tumlinson can you remove the .DS_Store files from the PR? These are Mac files.

**Review by clairekope — CHANGES_REQUESTED** [review]
New parameters look good. Techinically this PR doesn't address the minimum mass bug, as that was already handled by [a PR](https://github.com/foggie-sims/enzo-foggie/pull/7). 

The new log doesn't appear to replicate all messages from the old log. I leave it up to others whether or not that's acceptable.

A few changes:

- [x] document new parameters
- [x] remove .DS_Store files (already flagged in a separate comment but added here for efficiency)

**Comment by tumlinson** [comment]
@clairekope I deleted the .DS_store files and documented the two new parameters in the rst source of the docs.

**Comment by clairekope** [comment]
Docs look good but there are still `.DS_Store` files floating around. Check the "Files changed" tab

**Comment by tumlinson** [comment]
I think i got rid of all the DS_store files.

**Review by clochhaas — APPROVED** [review]
Looks good to me!

**Pull request merged**
